-- الراية للعطور — Supabase setup
-- شغّل هذا الملف كاملاً داخل Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'مستخدم',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  brand text default '',
  cat text default 'عطور',
  gender text default 'رجالي',
  size text default '',
  conc text default '',
  barcode text default '',
  code text default '',
  country text default '',
  qty numeric not null default 0,
  min numeric not null default 3,
  buy numeric not null default 0,
  wholesale numeric not null default 0,
  retail numeric not null default 0,
  supplier text default '',
  desc text default '',
  note text default '',
  aliases text[] not null default '{}',
  photo text default '',
  photo_path text default '',
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- إصلاح/ترقية: إذا كانت قاعدة البيانات القديمة لا تحتوي photo_path، أضف العمود بدون حذف البيانات.
alter table public.products add column if not exists photo_path text default '';

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.products(id) on delete set null,
  name text not null,
  qty numeric not null,
  total numeric not null,
  buy numeric not null default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.products(id) on delete set null,
  name text not null,
  qty numeric not null,
  price numeric not null,
  dealer text default '',
  invoice text default '',
  note text default '',
  photo text default '',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.notes (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  text text not null,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);


create table if not exists public.shortages (
  id uuid primary key default gen_random_uuid(), name text not null, qty numeric not null default 1, priority text not null default 'normal', note text default '', photo text default '', purchased boolean not null default false, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.debts (
  id uuid primary key default gen_random_uuid(), person text not null, phone text default '', amount numeric not null default 0, paid numeric not null default 0, note text default '', created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_name text not null default 'مستخدم',
  action text not null,
  entity_type text not null,
  entity_id text,
  entity_name text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.activity_log add column if not exists details jsonb not null default '{}'::jsonb;

create or replace function public.current_display_name()
returns text language sql stable as $$
  select coalesce((select display_name from public.profiles where id = auth.uid()), 'مستخدم')
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, display_name)
  values (new.id, coalesce(nullif(new.raw_user_meta_data->>'display_name',''), split_part(new.email,'@',1)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.log_activity()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  n text; oldj jsonb; newj jsonb; changes jsonb := '{}'::jsonb; k text; ov jsonb; nv jsonb;
begin
  n := case when tg_op='DELETE' then old.name else new.name end;
  if tg_op='UPDATE' then
    oldj := to_jsonb(old); newj := to_jsonb(new);
    for k in select key from jsonb_each(oldj) loop
      if k in ('updated_at','updated_by') then continue; end if;
      ov := oldj->k; nv := newj->k;
      if ov is distinct from nv then changes := changes || jsonb_build_object(k,jsonb_build_object('from',ov,'to',nv)); end if;
    end loop;
  elsif tg_op='INSERT' then
    changes := jsonb_build_object('created',true);
  else
    changes := jsonb_build_object('deleted',true);
  end if;
  insert into public.activity_log(user_id,user_name,action,entity_type,entity_id,entity_name,details)
  values (auth.uid(), public.current_display_name(), tg_op, tg_table_name,
          coalesce((case when tg_op='DELETE' then old.id else new.id end)::text,''), n,
          jsonb_build_object('changes',changes));
  return case when tg_op='DELETE' then old else new end;
end;
$$;

drop trigger if exists products_activity on public.products;
create trigger products_activity after insert or update or delete on public.products
for each row execute procedure public.log_activity();

create or replace function public.log_note_activity()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.activity_log(user_id,user_name,action,entity_type,entity_id,entity_name,details)
  values (auth.uid(), public.current_display_name(), tg_op, 'notes',
          coalesce((case when tg_op='DELETE' then old.id else new.id end)::text,''),
          case when tg_op='DELETE' then old.title else new.title end,
          jsonb_build_object('changes',jsonb_build_object('title',case when tg_op='DELETE' then old.title else new.title end)));
  return case when tg_op='DELETE' then old else new end;
end;
$$;
drop trigger if exists notes_activity on public.notes;
create trigger notes_activity after insert or update or delete on public.notes
for each row execute procedure public.log_note_activity();

create or replace function public.log_named_activity()
returns trigger language plpgsql security definer set search_path = public as $$
declare n text; oldj jsonb; newj jsonb; changes jsonb := '{}'::jsonb; k text; ov jsonb; nv jsonb;
begin
  n := case when tg_op='DELETE' then old.name else new.name end;
  if tg_op='UPDATE' then
    oldj := to_jsonb(old); newj := to_jsonb(new);
    for k in select key from jsonb_each(oldj) loop
      if k in ('created_at') then continue; end if;
      ov := oldj->k; nv := newj->k;
      if ov is distinct from nv then changes := changes || jsonb_build_object(k,jsonb_build_object('from',ov,'to',nv)); end if;
    end loop;
  elsif tg_op='INSERT' then changes := jsonb_build_object('created',true);
  else changes := jsonb_build_object('deleted',true); end if;
  insert into public.activity_log(user_id,user_name,action,entity_type,entity_id,entity_name,details)
  values (auth.uid(), public.current_display_name(), tg_op, tg_table_name,
          coalesce((case when tg_op='DELETE' then old.id else new.id end)::text,''), n,
          jsonb_build_object('changes',changes));
  return case when tg_op='DELETE' then old else new end;
end;
$$;

drop trigger if exists sales_activity on public.sales;
create trigger sales_activity after insert or update or delete on public.sales
for each row execute procedure public.log_named_activity();

drop trigger if exists purchases_activity on public.purchases;
create trigger purchases_activity after insert or update or delete on public.purchases
for each row execute procedure public.log_named_activity();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.purchases enable row level security;
alter table public.notes enable row level security;
alter table public.activity_log enable row level security;
alter table public.shortages enable row level security;
alter table public.debts enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (true);
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists products_all on public.products;
create policy products_all on public.products for all to authenticated using (true) with check (true);
drop policy if exists sales_all on public.sales;
create policy sales_all on public.sales for all to authenticated using (true) with check (true);
drop policy if exists purchases_all on public.purchases;
create policy purchases_all on public.purchases for all to authenticated using (true) with check (true);
drop policy if exists notes_all on public.notes;
create policy notes_all on public.notes for all to authenticated using (true) with check (true);
drop policy if exists activity_select on public.activity_log;
create policy activity_select on public.activity_log for select to authenticated using (true);
drop policy if exists shortages_all on public.shortages; create policy shortages_all on public.shortages for all to authenticated using (true) with check (true);
drop policy if exists debts_all on public.debts; create policy debts_all on public.debts for all to authenticated using (true) with check (true);

insert into storage.buckets (id,name,public)
values ('product-images','product-images',true)
on conflict (id) do update set public=true;

drop policy if exists product_images_read on storage.objects;
create policy product_images_read on storage.objects for select to public
using (bucket_id='product-images');

drop policy if exists product_images_insert on storage.objects;
create policy product_images_insert on storage.objects for insert to authenticated
with check (bucket_id='product-images');

drop policy if exists product_images_update on storage.objects;
create policy product_images_update on storage.objects for update to authenticated
using (bucket_id='product-images') with check (bucket_id='product-images');

drop policy if exists product_images_delete on storage.objects;
create policy product_images_delete on storage.objects for delete to authenticated
using (bucket_id='product-images');

-- فعّل Realtime للبيانات التي يجب أن تتحدث عند كل جهاز.
do $$ begin
  alter publication supabase_realtime add table public.products;
exception when duplicate_object then null;
end $$;

-- Realtime لكل الجداول التشغيلية.
do $$ begin alter publication supabase_realtime add table public.sales; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.purchases; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.notes; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.activity_log; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.shortages; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.debts; exception when duplicate_object then null; end $$;

notify pgrst, 'reload schema';

-- عمليات آمنة وذرّية: تحديث المخزون وتسجيل العملية في خطوة واحدة.
create or replace function public.record_sale(
  p_product_id uuid,
  p_qty numeric,
  p_price numeric
) returns void
language plpgsql
security invoker
set search_path = public
as $$
declare p public.products%rowtype;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_qty is null or p_qty <= 0 then raise exception 'INVALID_QTY'; end if;
  if p_price is null or p_price <= 0 then raise exception 'INVALID_PRICE'; end if;
  select * into p from public.products where id=p_product_id for update;
  if not found then raise exception 'PRODUCT_NOT_FOUND'; end if;
  if p.qty < p_qty then raise exception 'INSUFFICIENT_STOCK'; end if;
  update public.products
    set qty=p.qty-p_qty, updated_by=auth.uid(), updated_at=now()
    where id=p_product_id;
  insert into public.sales(product_id,name,qty,total,buy,created_by)
    values(p.id,p.name,p_qty,p_qty*p_price,p.buy,auth.uid());
end;
$$;

grant execute on function public.record_sale(uuid,numeric,numeric) to authenticated;

create or replace function public.record_purchase(
  p_product_id uuid,
  p_qty numeric,
  p_price numeric,
  p_dealer text default '',
  p_invoice text default '',
  p_note text default ''
) returns void
language plpgsql
security invoker
set search_path = public
as $$
declare p public.products%rowtype;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_qty is null or p_qty <= 0 then raise exception 'INVALID_QTY'; end if;
  if p_price is null or p_price < 0 then raise exception 'INVALID_PRICE'; end if;
  select * into p from public.products where id=p_product_id for update;
  if not found then raise exception 'PRODUCT_NOT_FOUND'; end if;
  update public.products
    set qty=p.qty+p_qty, buy=p_price, updated_by=auth.uid(), updated_at=now()
    where id=p_product_id;
  insert into public.purchases(product_id,name,qty,price,dealer,invoice,note,created_by)
    values(p.id,p.name,p_qty,p_price,coalesce(p_dealer,''),coalesce(p_invoice,''),coalesce(p_note,''),auth.uid());
end;
$$;

grant execute on function public.record_purchase(uuid,numeric,numeric,text,text,text) to authenticated;

-- منع التكرار الحقيقي للباركود والكود عند تعبئتهما.
do $$ begin
  create unique index products_barcode_unique on public.products (barcode)
    where nullif(trim(barcode),'') is not null;
exception when duplicate_object then null; when unique_violation then
  raise notice 'يوجد باركودات مكررة؛ تم تجاوز الفهرس حتى لا تتوقف الترقية.';
end $$;
do $$ begin
  create unique index products_code_unique on public.products (code)
    where nullif(trim(code),'') is not null;
exception when duplicate_object then null; when unique_violation then
  raise notice 'توجد أكواد أصناف مكررة؛ تم تجاوز الفهرس حتى لا تتوقف الترقية.';
end $$;

notify pgrst, 'reload schema';

-- دعم صورة اختيارية للنقوصات
alter table public.shortages add column if not exists photo text default '';
notify pgrst, 'reload schema';


-- الراية للعطور — إعداد خلطات العطور V11
-- الراية للعطور — V11: إصلاح التخزين السحابي + وصف الخلطة
create table if not exists public.mixes (
  id uuid primary key default gen_random_uuid(), name text not null,
  gender text not null check (gender in ('رجالي','نسائي','كلا الجنسين')),
  desc text default '', photo text default '', photo_path text default '',
  created_by uuid references auth.users(id), created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.mixes add column if not exists desc text default '';
alter table public.mixes add column if not exists photo_path text default '';
create table if not exists public.mix_items (
  id uuid primary key default gen_random_uuid(),
  mix_id uuid not null references public.mixes(id) on delete cascade,
  product_id uuid null references public.products(id) on delete set null,
  perfume_name text, position integer not null check (position between 1 and 10),
  unique (mix_id, position)
);
alter table public.mix_items add column if not exists perfume_name text;
alter table public.mix_items alter column product_id drop not null;
update public.mix_items mi set perfume_name=p.name from public.products p
where mi.product_id=p.id and nullif(trim(mi.perfume_name),'') is null;
delete from public.mix_items where nullif(trim(perfume_name),'') is null;
alter table public.mix_items alter column perfume_name set not null;

drop function if exists public.save_mixture(uuid,text,text,text,uuid[]);
create or replace function public.save_mixture(
 p_id uuid,p_name text,p_desc text,p_gender text,p_photo text,p_perfume_names text[]
) returns uuid language plpgsql security invoker set search_path=public as $$
declare v_id uuid; v_count integer; v_name text; i integer:=0;
begin
 if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
 if nullif(trim(p_name),'') is null then raise exception 'INVALID_NAME'; end if;
 if p_gender not in ('رجالي','نسائي','كلا الجنسين') then raise exception 'INVALID_GENDER'; end if;
 if p_perfume_names is null then raise exception 'INVALID_PERFUMES'; end if;
 select count(*) into v_count from unnest(p_perfume_names) x where nullif(trim(x),'') is not null;
 if v_count<2 or v_count>10 then raise exception 'MIX_MUST_HAVE_2_TO_10'; end if;
 if v_count<>(select count(distinct lower(trim(x))) from unnest(p_perfume_names) x where nullif(trim(x),'') is not null)
 then raise exception 'DUPLICATE_PERFUME_NAME'; end if;
 if p_id is null then
   insert into public.mixes(name,desc,gender,photo,created_by)
   values(trim(p_name),coalesce(trim(p_desc),''),p_gender,coalesce(p_photo,''),auth.uid()) returning id into v_id;
 else
   v_id:=p_id;
   update public.mixes set name=trim(p_name),desc=coalesce(trim(p_desc),''),gender=p_gender,photo=coalesce(p_photo,''),updated_at=now()
   where id=v_id;
   if not found then raise exception 'MIX_NOT_FOUND'; end if;
   delete from public.mix_items where mix_id=v_id;
 end if;
 foreach v_name in array p_perfume_names loop
   if nullif(trim(v_name),'') is not null then
     i:=i+1; insert into public.mix_items(mix_id,perfume_name,position) values(v_id,trim(v_name),i);
   end if;
 end loop;
 return v_id;
end; $$;
grant execute on function public.save_mixture(uuid,text,text,text,text,text[]) to authenticated;
alter table public.mixes enable row level security; alter table public.mix_items enable row level security;
drop policy if exists mixes_all on public.mixes;
create policy mixes_all on public.mixes for all to authenticated using(true) with check(true);
drop policy if exists mix_items_all on public.mix_items;
create policy mix_items_all on public.mix_items for all to authenticated using(true) with check(true);
drop trigger if exists mixes_activity on public.mixes;
create trigger mixes_activity after insert or update or delete on public.mixes for each row execute procedure public.log_activity();
do $$ begin alter publication supabase_realtime add table public.mixes; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.mix_items; exception when duplicate_object then null; end $$;
notify pgrst,'reload schema';
